# Generated by Django 2.2.1 on 2019-05-23 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190523_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 18, 55, 25, 608246), verbose_name='date published'),
        ),
    ]
